// AUTO-GENERATED by scripts/generate-timezones.mjs — do not hand-edit.
// Source: Intl.supportedValuesOf("timeZone") — the live IANA/ICU database.
// Re-run the script to pick up new/renamed zones. Zero manual city entry.

export interface TZCity {
  slug: string;
  city: string;
  region: string; // IANA area, e.g. "America", "Asia", "Europe" — used for search grouping
  tz: string;      // canonical IANA timezone name
}

// Every IANA timezone Node/ICU knows about — 445 entries, auto-sourced.
export const ALL_TIMEZONES: TZCity[] = [
  {
    "slug": "abidjan",
    "city": "Abidjan",
    "region": "Africa",
    "tz": "Africa/Abidjan"
  },
  {
    "slug": "accra",
    "city": "Accra",
    "region": "Africa",
    "tz": "Africa/Accra"
  },
  {
    "slug": "adak",
    "city": "Adak",
    "region": "America",
    "tz": "America/Adak"
  },
  {
    "slug": "addis-ababa",
    "city": "Addis Ababa",
    "region": "Africa",
    "tz": "Africa/Addis_Ababa"
  },
  {
    "slug": "adelaide",
    "city": "Adelaide",
    "region": "Australia",
    "tz": "Australia/Adelaide"
  },
  {
    "slug": "aden",
    "city": "Aden",
    "region": "Asia",
    "tz": "Asia/Aden"
  },
  {
    "slug": "algiers",
    "city": "Algiers",
    "region": "Africa",
    "tz": "Africa/Algiers"
  },
  {
    "slug": "almaty",
    "city": "Almaty",
    "region": "Asia",
    "tz": "Asia/Almaty"
  },
  {
    "slug": "amman",
    "city": "Amman",
    "region": "Asia",
    "tz": "Asia/Amman"
  },
  {
    "slug": "amsterdam",
    "city": "Amsterdam",
    "region": "Europe",
    "tz": "Europe/Amsterdam"
  },
  {
    "slug": "anadyr",
    "city": "Anadyr",
    "region": "Asia",
    "tz": "Asia/Anadyr"
  },
  {
    "slug": "anchorage",
    "city": "Anchorage",
    "region": "America",
    "tz": "America/Anchorage"
  },
  {
    "slug": "andorra",
    "city": "Andorra",
    "region": "Europe",
    "tz": "Europe/Andorra"
  },
  {
    "slug": "anguilla",
    "city": "Anguilla",
    "region": "America",
    "tz": "America/Anguilla"
  },
  {
    "slug": "antananarivo",
    "city": "Antananarivo",
    "region": "Indian",
    "tz": "Indian/Antananarivo"
  },
  {
    "slug": "antigua",
    "city": "Antigua",
    "region": "America",
    "tz": "America/Antigua"
  },
  {
    "slug": "apia",
    "city": "Apia",
    "region": "Pacific",
    "tz": "Pacific/Apia"
  },
  {
    "slug": "aqtau",
    "city": "Aqtau",
    "region": "Asia",
    "tz": "Asia/Aqtau"
  },
  {
    "slug": "aqtobe",
    "city": "Aqtobe",
    "region": "Asia",
    "tz": "Asia/Aqtobe"
  },
  {
    "slug": "araguaina",
    "city": "Araguaina",
    "region": "America",
    "tz": "America/Araguaina"
  },
  {
    "slug": "aruba",
    "city": "Aruba",
    "region": "America",
    "tz": "America/Aruba"
  },
  {
    "slug": "ashgabat",
    "city": "Ashgabat",
    "region": "Asia",
    "tz": "Asia/Ashgabat"
  },
  {
    "slug": "asmera",
    "city": "Asmera",
    "region": "Africa",
    "tz": "Africa/Asmera"
  },
  {
    "slug": "astrakhan",
    "city": "Astrakhan",
    "region": "Europe",
    "tz": "Europe/Astrakhan"
  },
  {
    "slug": "asuncion",
    "city": "Asuncion",
    "region": "America",
    "tz": "America/Asuncion"
  },
  {
    "slug": "athens",
    "city": "Athens",
    "region": "Europe",
    "tz": "Europe/Athens"
  },
  {
    "slug": "atyrau",
    "city": "Atyrau",
    "region": "Asia",
    "tz": "Asia/Atyrau"
  },
  {
    "slug": "auckland",
    "city": "Auckland",
    "region": "Pacific",
    "tz": "Pacific/Auckland"
  },
  {
    "slug": "azores",
    "city": "Azores",
    "region": "Atlantic",
    "tz": "Atlantic/Azores"
  },
  {
    "slug": "baghdad",
    "city": "Baghdad",
    "region": "Asia",
    "tz": "Asia/Baghdad"
  },
  {
    "slug": "bahia",
    "city": "Bahia",
    "region": "America",
    "tz": "America/Bahia"
  },
  {
    "slug": "bahia-banderas",
    "city": "Bahia Banderas",
    "region": "America",
    "tz": "America/Bahia_Banderas"
  },
  {
    "slug": "bahrain",
    "city": "Bahrain",
    "region": "Asia",
    "tz": "Asia/Bahrain"
  },
  {
    "slug": "baku",
    "city": "Baku",
    "region": "Asia",
    "tz": "Asia/Baku"
  },
  {
    "slug": "bamako",
    "city": "Bamako",
    "region": "Africa",
    "tz": "Africa/Bamako"
  },
  {
    "slug": "bangkok",
    "city": "Bangkok",
    "region": "Asia",
    "tz": "Asia/Bangkok"
  },
  {
    "slug": "bangui",
    "city": "Bangui",
    "region": "Africa",
    "tz": "Africa/Bangui"
  },
  {
    "slug": "banjul",
    "city": "Banjul",
    "region": "Africa",
    "tz": "Africa/Banjul"
  },
  {
    "slug": "barbados",
    "city": "Barbados",
    "region": "America",
    "tz": "America/Barbados"
  },
  {
    "slug": "barnaul",
    "city": "Barnaul",
    "region": "Asia",
    "tz": "Asia/Barnaul"
  },
  {
    "slug": "beirut",
    "city": "Beirut",
    "region": "Asia",
    "tz": "Asia/Beirut"
  },
  {
    "slug": "belem",
    "city": "Belem",
    "region": "America",
    "tz": "America/Belem"
  },
  {
    "slug": "belgrade",
    "city": "Belgrade",
    "region": "Europe",
    "tz": "Europe/Belgrade"
  },
  {
    "slug": "belize",
    "city": "Belize",
    "region": "America",
    "tz": "America/Belize"
  },
  {
    "slug": "berlin",
    "city": "Berlin",
    "region": "Europe",
    "tz": "Europe/Berlin"
  },
  {
    "slug": "bermuda",
    "city": "Bermuda",
    "region": "Atlantic",
    "tz": "Atlantic/Bermuda"
  },
  {
    "slug": "beulah",
    "city": "Beulah",
    "region": "America",
    "tz": "America/North_Dakota/Beulah"
  },
  {
    "slug": "bishkek",
    "city": "Bishkek",
    "region": "Asia",
    "tz": "Asia/Bishkek"
  },
  {
    "slug": "bissau",
    "city": "Bissau",
    "region": "Africa",
    "tz": "Africa/Bissau"
  },
  {
    "slug": "blanc-sablon",
    "city": "Blanc-Sablon",
    "region": "America",
    "tz": "America/Blanc-Sablon"
  },
  {
    "slug": "blantyre",
    "city": "Blantyre",
    "region": "Africa",
    "tz": "Africa/Blantyre"
  },
  {
    "slug": "boa-vista",
    "city": "Boa Vista",
    "region": "America",
    "tz": "America/Boa_Vista"
  },
  {
    "slug": "bogota",
    "city": "Bogota",
    "region": "America",
    "tz": "America/Bogota"
  },
  {
    "slug": "boise",
    "city": "Boise",
    "region": "America",
    "tz": "America/Boise"
  },
  {
    "slug": "bougainville",
    "city": "Bougainville",
    "region": "Pacific",
    "tz": "Pacific/Bougainville"
  },
  {
    "slug": "bratislava",
    "city": "Bratislava",
    "region": "Europe",
    "tz": "Europe/Bratislava"
  },
  {
    "slug": "brazzaville",
    "city": "Brazzaville",
    "region": "Africa",
    "tz": "Africa/Brazzaville"
  },
  {
    "slug": "brisbane",
    "city": "Brisbane",
    "region": "Australia",
    "tz": "Australia/Brisbane"
  },
  {
    "slug": "broken-hill",
    "city": "Broken Hill",
    "region": "Australia",
    "tz": "Australia/Broken_Hill"
  },
  {
    "slug": "brunei",
    "city": "Brunei",
    "region": "Asia",
    "tz": "Asia/Brunei"
  },
  {
    "slug": "brussels",
    "city": "Brussels",
    "region": "Europe",
    "tz": "Europe/Brussels"
  },
  {
    "slug": "bucharest",
    "city": "Bucharest",
    "region": "Europe",
    "tz": "Europe/Bucharest"
  },
  {
    "slug": "budapest",
    "city": "Budapest",
    "region": "Europe",
    "tz": "Europe/Budapest"
  },
  {
    "slug": "buenos-aires",
    "city": "Buenos Aires",
    "region": "America",
    "tz": "America/Buenos_Aires"
  },
  {
    "slug": "bujumbura",
    "city": "Bujumbura",
    "region": "Africa",
    "tz": "Africa/Bujumbura"
  },
  {
    "slug": "busingen",
    "city": "Busingen",
    "region": "Europe",
    "tz": "Europe/Busingen"
  },
  {
    "slug": "cairo",
    "city": "Cairo",
    "region": "Africa",
    "tz": "Africa/Cairo"
  },
  {
    "slug": "calcutta",
    "city": "Calcutta",
    "region": "Asia",
    "tz": "Asia/Calcutta"
  },
  {
    "slug": "cambridge-bay",
    "city": "Cambridge Bay",
    "region": "America",
    "tz": "America/Cambridge_Bay"
  },
  {
    "slug": "campo-grande",
    "city": "Campo Grande",
    "region": "America",
    "tz": "America/Campo_Grande"
  },
  {
    "slug": "canary",
    "city": "Canary",
    "region": "Atlantic",
    "tz": "Atlantic/Canary"
  },
  {
    "slug": "cancun",
    "city": "Cancun",
    "region": "America",
    "tz": "America/Cancun"
  },
  {
    "slug": "cape-verde",
    "city": "Cape Verde",
    "region": "Atlantic",
    "tz": "Atlantic/Cape_Verde"
  },
  {
    "slug": "caracas",
    "city": "Caracas",
    "region": "America",
    "tz": "America/Caracas"
  },
  {
    "slug": "casablanca",
    "city": "Casablanca",
    "region": "Africa",
    "tz": "Africa/Casablanca"
  },
  {
    "slug": "casey",
    "city": "Casey",
    "region": "Antarctica",
    "tz": "Antarctica/Casey"
  },
  {
    "slug": "catamarca",
    "city": "Catamarca",
    "region": "America",
    "tz": "America/Catamarca"
  },
  {
    "slug": "cayenne",
    "city": "Cayenne",
    "region": "America",
    "tz": "America/Cayenne"
  },
  {
    "slug": "cayman",
    "city": "Cayman",
    "region": "America",
    "tz": "America/Cayman"
  },
  {
    "slug": "center",
    "city": "Center",
    "region": "America",
    "tz": "America/North_Dakota/Center"
  },
  {
    "slug": "ceuta",
    "city": "Ceuta",
    "region": "Africa",
    "tz": "Africa/Ceuta"
  },
  {
    "slug": "chagos",
    "city": "Chagos",
    "region": "Indian",
    "tz": "Indian/Chagos"
  },
  {
    "slug": "chatham",
    "city": "Chatham",
    "region": "Pacific",
    "tz": "Pacific/Chatham"
  },
  {
    "slug": "chicago",
    "city": "Chicago",
    "region": "America",
    "tz": "America/Chicago"
  },
  {
    "slug": "chihuahua",
    "city": "Chihuahua",
    "region": "America",
    "tz": "America/Chihuahua"
  },
  {
    "slug": "chisinau",
    "city": "Chisinau",
    "region": "Europe",
    "tz": "Europe/Chisinau"
  },
  {
    "slug": "chita",
    "city": "Chita",
    "region": "Asia",
    "tz": "Asia/Chita"
  },
  {
    "slug": "christmas",
    "city": "Christmas",
    "region": "Indian",
    "tz": "Indian/Christmas"
  },
  {
    "slug": "ciudad-juarez",
    "city": "Ciudad Juarez",
    "region": "America",
    "tz": "America/Ciudad_Juarez"
  },
  {
    "slug": "cocos",
    "city": "Cocos",
    "region": "Indian",
    "tz": "Indian/Cocos"
  },
  {
    "slug": "colombo",
    "city": "Colombo",
    "region": "Asia",
    "tz": "Asia/Colombo"
  },
  {
    "slug": "comoro",
    "city": "Comoro",
    "region": "Indian",
    "tz": "Indian/Comoro"
  },
  {
    "slug": "conakry",
    "city": "Conakry",
    "region": "Africa",
    "tz": "Africa/Conakry"
  },
  {
    "slug": "copenhagen",
    "city": "Copenhagen",
    "region": "Europe",
    "tz": "Europe/Copenhagen"
  },
  {
    "slug": "coral-harbour",
    "city": "Coral Harbour",
    "region": "America",
    "tz": "America/Coral_Harbour"
  },
  {
    "slug": "cordoba",
    "city": "Cordoba",
    "region": "America",
    "tz": "America/Cordoba"
  },
  {
    "slug": "costa-rica",
    "city": "Costa Rica",
    "region": "America",
    "tz": "America/Costa_Rica"
  },
  {
    "slug": "coyhaique",
    "city": "Coyhaique",
    "region": "America",
    "tz": "America/Coyhaique"
  },
  {
    "slug": "creston",
    "city": "Creston",
    "region": "America",
    "tz": "America/Creston"
  },
  {
    "slug": "cuiaba",
    "city": "Cuiaba",
    "region": "America",
    "tz": "America/Cuiaba"
  },
  {
    "slug": "curacao",
    "city": "Curacao",
    "region": "America",
    "tz": "America/Curacao"
  },
  {
    "slug": "dakar",
    "city": "Dakar",
    "region": "Africa",
    "tz": "Africa/Dakar"
  },
  {
    "slug": "damascus",
    "city": "Damascus",
    "region": "Asia",
    "tz": "Asia/Damascus"
  },
  {
    "slug": "danmarkshavn",
    "city": "Danmarkshavn",
    "region": "America",
    "tz": "America/Danmarkshavn"
  },
  {
    "slug": "dar-es-salaam",
    "city": "Dar es Salaam",
    "region": "Africa",
    "tz": "Africa/Dar_es_Salaam"
  },
  {
    "slug": "darwin",
    "city": "Darwin",
    "region": "Australia",
    "tz": "Australia/Darwin"
  },
  {
    "slug": "davis",
    "city": "Davis",
    "region": "Antarctica",
    "tz": "Antarctica/Davis"
  },
  {
    "slug": "dawson",
    "city": "Dawson",
    "region": "America",
    "tz": "America/Dawson"
  },
  {
    "slug": "dawson-creek",
    "city": "Dawson Creek",
    "region": "America",
    "tz": "America/Dawson_Creek"
  },
  {
    "slug": "denver",
    "city": "Denver",
    "region": "America",
    "tz": "America/Denver"
  },
  {
    "slug": "detroit",
    "city": "Detroit",
    "region": "America",
    "tz": "America/Detroit"
  },
  {
    "slug": "dhaka",
    "city": "Dhaka",
    "region": "Asia",
    "tz": "Asia/Dhaka"
  },
  {
    "slug": "dili",
    "city": "Dili",
    "region": "Asia",
    "tz": "Asia/Dili"
  },
  {
    "slug": "djibouti",
    "city": "Djibouti",
    "region": "Africa",
    "tz": "Africa/Djibouti"
  },
  {
    "slug": "dominica",
    "city": "Dominica",
    "region": "America",
    "tz": "America/Dominica"
  },
  {
    "slug": "douala",
    "city": "Douala",
    "region": "Africa",
    "tz": "Africa/Douala"
  },
  {
    "slug": "dubai",
    "city": "Dubai",
    "region": "Asia",
    "tz": "Asia/Dubai"
  },
  {
    "slug": "dublin",
    "city": "Dublin",
    "region": "Europe",
    "tz": "Europe/Dublin"
  },
  {
    "slug": "dumontdurville",
    "city": "DumontDUrville",
    "region": "Antarctica",
    "tz": "Antarctica/DumontDUrville"
  },
  {
    "slug": "dushanbe",
    "city": "Dushanbe",
    "region": "Asia",
    "tz": "Asia/Dushanbe"
  },
  {
    "slug": "easter",
    "city": "Easter",
    "region": "Pacific",
    "tz": "Pacific/Easter"
  },
  {
    "slug": "edmonton",
    "city": "Edmonton",
    "region": "America",
    "tz": "America/Edmonton"
  },
  {
    "slug": "efate",
    "city": "Efate",
    "region": "Pacific",
    "tz": "Pacific/Efate"
  },
  {
    "slug": "eirunepe",
    "city": "Eirunepe",
    "region": "America",
    "tz": "America/Eirunepe"
  },
  {
    "slug": "el-aaiun",
    "city": "El Aaiun",
    "region": "Africa",
    "tz": "Africa/El_Aaiun"
  },
  {
    "slug": "el-salvador",
    "city": "El Salvador",
    "region": "America",
    "tz": "America/El_Salvador"
  },
  {
    "slug": "enderbury",
    "city": "Enderbury",
    "region": "Pacific",
    "tz": "Pacific/Enderbury"
  },
  {
    "slug": "eucla",
    "city": "Eucla",
    "region": "Australia",
    "tz": "Australia/Eucla"
  },
  {
    "slug": "faeroe",
    "city": "Faeroe",
    "region": "Atlantic",
    "tz": "Atlantic/Faeroe"
  },
  {
    "slug": "fakaofo",
    "city": "Fakaofo",
    "region": "Pacific",
    "tz": "Pacific/Fakaofo"
  },
  {
    "slug": "famagusta",
    "city": "Famagusta",
    "region": "Asia",
    "tz": "Asia/Famagusta"
  },
  {
    "slug": "fiji",
    "city": "Fiji",
    "region": "Pacific",
    "tz": "Pacific/Fiji"
  },
  {
    "slug": "fort-nelson",
    "city": "Fort Nelson",
    "region": "America",
    "tz": "America/Fort_Nelson"
  },
  {
    "slug": "fortaleza",
    "city": "Fortaleza",
    "region": "America",
    "tz": "America/Fortaleza"
  },
  {
    "slug": "freetown",
    "city": "Freetown",
    "region": "Africa",
    "tz": "Africa/Freetown"
  },
  {
    "slug": "funafuti",
    "city": "Funafuti",
    "region": "Pacific",
    "tz": "Pacific/Funafuti"
  },
  {
    "slug": "gaborone",
    "city": "Gaborone",
    "region": "Africa",
    "tz": "Africa/Gaborone"
  },
  {
    "slug": "galapagos",
    "city": "Galapagos",
    "region": "Pacific",
    "tz": "Pacific/Galapagos"
  },
  {
    "slug": "gambier",
    "city": "Gambier",
    "region": "Pacific",
    "tz": "Pacific/Gambier"
  },
  {
    "slug": "gaza",
    "city": "Gaza",
    "region": "Asia",
    "tz": "Asia/Gaza"
  },
  {
    "slug": "gibraltar",
    "city": "Gibraltar",
    "region": "Europe",
    "tz": "Europe/Gibraltar"
  },
  {
    "slug": "glace-bay",
    "city": "Glace Bay",
    "region": "America",
    "tz": "America/Glace_Bay"
  },
  {
    "slug": "godthab",
    "city": "Godthab",
    "region": "America",
    "tz": "America/Godthab"
  },
  {
    "slug": "goose-bay",
    "city": "Goose Bay",
    "region": "America",
    "tz": "America/Goose_Bay"
  },
  {
    "slug": "grand-turk",
    "city": "Grand Turk",
    "region": "America",
    "tz": "America/Grand_Turk"
  },
  {
    "slug": "grenada",
    "city": "Grenada",
    "region": "America",
    "tz": "America/Grenada"
  },
  {
    "slug": "guadalcanal",
    "city": "Guadalcanal",
    "region": "Pacific",
    "tz": "Pacific/Guadalcanal"
  },
  {
    "slug": "guadeloupe",
    "city": "Guadeloupe",
    "region": "America",
    "tz": "America/Guadeloupe"
  },
  {
    "slug": "guam",
    "city": "Guam",
    "region": "Pacific",
    "tz": "Pacific/Guam"
  },
  {
    "slug": "guatemala",
    "city": "Guatemala",
    "region": "America",
    "tz": "America/Guatemala"
  },
  {
    "slug": "guayaquil",
    "city": "Guayaquil",
    "region": "America",
    "tz": "America/Guayaquil"
  },
  {
    "slug": "guernsey",
    "city": "Guernsey",
    "region": "Europe",
    "tz": "Europe/Guernsey"
  },
  {
    "slug": "guyana",
    "city": "Guyana",
    "region": "America",
    "tz": "America/Guyana"
  },
  {
    "slug": "halifax",
    "city": "Halifax",
    "region": "America",
    "tz": "America/Halifax"
  },
  {
    "slug": "harare",
    "city": "Harare",
    "region": "Africa",
    "tz": "Africa/Harare"
  },
  {
    "slug": "havana",
    "city": "Havana",
    "region": "America",
    "tz": "America/Havana"
  },
  {
    "slug": "hebron",
    "city": "Hebron",
    "region": "Asia",
    "tz": "Asia/Hebron"
  },
  {
    "slug": "helsinki",
    "city": "Helsinki",
    "region": "Europe",
    "tz": "Europe/Helsinki"
  },
  {
    "slug": "hermosillo",
    "city": "Hermosillo",
    "region": "America",
    "tz": "America/Hermosillo"
  },
  {
    "slug": "hobart",
    "city": "Hobart",
    "region": "Australia",
    "tz": "Australia/Hobart"
  },
  {
    "slug": "hong-kong",
    "city": "Hong Kong",
    "region": "Asia",
    "tz": "Asia/Hong_Kong"
  },
  {
    "slug": "honolulu",
    "city": "Honolulu",
    "region": "Pacific",
    "tz": "Pacific/Honolulu"
  },
  {
    "slug": "hovd",
    "city": "Hovd",
    "region": "Asia",
    "tz": "Asia/Hovd"
  },
  {
    "slug": "indianapolis",
    "city": "Indianapolis",
    "region": "America",
    "tz": "America/Indianapolis"
  },
  {
    "slug": "inuvik",
    "city": "Inuvik",
    "region": "America",
    "tz": "America/Inuvik"
  },
  {
    "slug": "iqaluit",
    "city": "Iqaluit",
    "region": "America",
    "tz": "America/Iqaluit"
  },
  {
    "slug": "irkutsk",
    "city": "Irkutsk",
    "region": "Asia",
    "tz": "Asia/Irkutsk"
  },
  {
    "slug": "isle-of-man",
    "city": "Isle of Man",
    "region": "Europe",
    "tz": "Europe/Isle_of_Man"
  },
  {
    "slug": "istanbul",
    "city": "Istanbul",
    "region": "Europe",
    "tz": "Europe/Istanbul"
  },
  {
    "slug": "jakarta",
    "city": "Jakarta",
    "region": "Asia",
    "tz": "Asia/Jakarta"
  },
  {
    "slug": "jamaica",
    "city": "Jamaica",
    "region": "America",
    "tz": "America/Jamaica"
  },
  {
    "slug": "jayapura",
    "city": "Jayapura",
    "region": "Asia",
    "tz": "Asia/Jayapura"
  },
  {
    "slug": "jersey",
    "city": "Jersey",
    "region": "Europe",
    "tz": "Europe/Jersey"
  },
  {
    "slug": "jerusalem",
    "city": "Jerusalem",
    "region": "Asia",
    "tz": "Asia/Jerusalem"
  },
  {
    "slug": "johannesburg",
    "city": "Johannesburg",
    "region": "Africa",
    "tz": "Africa/Johannesburg"
  },
  {
    "slug": "juba",
    "city": "Juba",
    "region": "Africa",
    "tz": "Africa/Juba"
  },
  {
    "slug": "jujuy",
    "city": "Jujuy",
    "region": "America",
    "tz": "America/Jujuy"
  },
  {
    "slug": "juneau",
    "city": "Juneau",
    "region": "America",
    "tz": "America/Juneau"
  },
  {
    "slug": "kabul",
    "city": "Kabul",
    "region": "Asia",
    "tz": "Asia/Kabul"
  },
  {
    "slug": "kaliningrad",
    "city": "Kaliningrad",
    "region": "Europe",
    "tz": "Europe/Kaliningrad"
  },
  {
    "slug": "kamchatka",
    "city": "Kamchatka",
    "region": "Asia",
    "tz": "Asia/Kamchatka"
  },
  {
    "slug": "kampala",
    "city": "Kampala",
    "region": "Africa",
    "tz": "Africa/Kampala"
  },
  {
    "slug": "karachi",
    "city": "Karachi",
    "region": "Asia",
    "tz": "Asia/Karachi"
  },
  {
    "slug": "katmandu",
    "city": "Katmandu",
    "region": "Asia",
    "tz": "Asia/Katmandu"
  },
  {
    "slug": "kerguelen",
    "city": "Kerguelen",
    "region": "Indian",
    "tz": "Indian/Kerguelen"
  },
  {
    "slug": "khandyga",
    "city": "Khandyga",
    "region": "Asia",
    "tz": "Asia/Khandyga"
  },
  {
    "slug": "khartoum",
    "city": "Khartoum",
    "region": "Africa",
    "tz": "Africa/Khartoum"
  },
  {
    "slug": "kiev",
    "city": "Kiev",
    "region": "Europe",
    "tz": "Europe/Kiev"
  },
  {
    "slug": "kigali",
    "city": "Kigali",
    "region": "Africa",
    "tz": "Africa/Kigali"
  },
  {
    "slug": "kinshasa",
    "city": "Kinshasa",
    "region": "Africa",
    "tz": "Africa/Kinshasa"
  },
  {
    "slug": "kiritimati",
    "city": "Kiritimati",
    "region": "Pacific",
    "tz": "Pacific/Kiritimati"
  },
  {
    "slug": "kirov",
    "city": "Kirov",
    "region": "Europe",
    "tz": "Europe/Kirov"
  },
  {
    "slug": "knox",
    "city": "Knox",
    "region": "America",
    "tz": "America/Indiana/Knox"
  },
  {
    "slug": "kosrae",
    "city": "Kosrae",
    "region": "Pacific",
    "tz": "Pacific/Kosrae"
  },
  {
    "slug": "kralendijk",
    "city": "Kralendijk",
    "region": "America",
    "tz": "America/Kralendijk"
  },
  {
    "slug": "krasnoyarsk",
    "city": "Krasnoyarsk",
    "region": "Asia",
    "tz": "Asia/Krasnoyarsk"
  },
  {
    "slug": "kuala-lumpur",
    "city": "Kuala Lumpur",
    "region": "Asia",
    "tz": "Asia/Kuala_Lumpur"
  },
  {
    "slug": "kuching",
    "city": "Kuching",
    "region": "Asia",
    "tz": "Asia/Kuching"
  },
  {
    "slug": "kuwait",
    "city": "Kuwait",
    "region": "Asia",
    "tz": "Asia/Kuwait"
  },
  {
    "slug": "kwajalein",
    "city": "Kwajalein",
    "region": "Pacific",
    "tz": "Pacific/Kwajalein"
  },
  {
    "slug": "la-paz",
    "city": "La Paz",
    "region": "America",
    "tz": "America/La_Paz"
  },
  {
    "slug": "la-rioja",
    "city": "La Rioja",
    "region": "America",
    "tz": "America/Argentina/La_Rioja"
  },
  {
    "slug": "lagos",
    "city": "Lagos",
    "region": "Africa",
    "tz": "Africa/Lagos"
  },
  {
    "slug": "libreville",
    "city": "Libreville",
    "region": "Africa",
    "tz": "Africa/Libreville"
  },
  {
    "slug": "lima",
    "city": "Lima",
    "region": "America",
    "tz": "America/Lima"
  },
  {
    "slug": "lindeman",
    "city": "Lindeman",
    "region": "Australia",
    "tz": "Australia/Lindeman"
  },
  {
    "slug": "lisbon",
    "city": "Lisbon",
    "region": "Europe",
    "tz": "Europe/Lisbon"
  },
  {
    "slug": "ljubljana",
    "city": "Ljubljana",
    "region": "Europe",
    "tz": "Europe/Ljubljana"
  },
  {
    "slug": "lome",
    "city": "Lome",
    "region": "Africa",
    "tz": "Africa/Lome"
  },
  {
    "slug": "london",
    "city": "London",
    "region": "Europe",
    "tz": "Europe/London"
  },
  {
    "slug": "longyearbyen",
    "city": "Longyearbyen",
    "region": "Arctic",
    "tz": "Arctic/Longyearbyen"
  },
  {
    "slug": "lord-howe",
    "city": "Lord Howe",
    "region": "Australia",
    "tz": "Australia/Lord_Howe"
  },
  {
    "slug": "los-angeles",
    "city": "Los Angeles",
    "region": "America",
    "tz": "America/Los_Angeles"
  },
  {
    "slug": "louisville",
    "city": "Louisville",
    "region": "America",
    "tz": "America/Louisville"
  },
  {
    "slug": "lower-princes",
    "city": "Lower Princes",
    "region": "America",
    "tz": "America/Lower_Princes"
  },
  {
    "slug": "luanda",
    "city": "Luanda",
    "region": "Africa",
    "tz": "Africa/Luanda"
  },
  {
    "slug": "lubumbashi",
    "city": "Lubumbashi",
    "region": "Africa",
    "tz": "Africa/Lubumbashi"
  },
  {
    "slug": "lusaka",
    "city": "Lusaka",
    "region": "Africa",
    "tz": "Africa/Lusaka"
  },
  {
    "slug": "luxembourg",
    "city": "Luxembourg",
    "region": "Europe",
    "tz": "Europe/Luxembourg"
  },
  {
    "slug": "macau",
    "city": "Macau",
    "region": "Asia",
    "tz": "Asia/Macau"
  },
  {
    "slug": "maceio",
    "city": "Maceio",
    "region": "America",
    "tz": "America/Maceio"
  },
  {
    "slug": "macquarie",
    "city": "Macquarie",
    "region": "Antarctica",
    "tz": "Antarctica/Macquarie"
  },
  {
    "slug": "madeira",
    "city": "Madeira",
    "region": "Atlantic",
    "tz": "Atlantic/Madeira"
  },
  {
    "slug": "madrid",
    "city": "Madrid",
    "region": "Europe",
    "tz": "Europe/Madrid"
  },
  {
    "slug": "magadan",
    "city": "Magadan",
    "region": "Asia",
    "tz": "Asia/Magadan"
  },
  {
    "slug": "mahe",
    "city": "Mahe",
    "region": "Indian",
    "tz": "Indian/Mahe"
  },
  {
    "slug": "majuro",
    "city": "Majuro",
    "region": "Pacific",
    "tz": "Pacific/Majuro"
  },
  {
    "slug": "makassar",
    "city": "Makassar",
    "region": "Asia",
    "tz": "Asia/Makassar"
  },
  {
    "slug": "malabo",
    "city": "Malabo",
    "region": "Africa",
    "tz": "Africa/Malabo"
  },
  {
    "slug": "maldives",
    "city": "Maldives",
    "region": "Indian",
    "tz": "Indian/Maldives"
  },
  {
    "slug": "malta",
    "city": "Malta",
    "region": "Europe",
    "tz": "Europe/Malta"
  },
  {
    "slug": "managua",
    "city": "Managua",
    "region": "America",
    "tz": "America/Managua"
  },
  {
    "slug": "manaus",
    "city": "Manaus",
    "region": "America",
    "tz": "America/Manaus"
  },
  {
    "slug": "manila",
    "city": "Manila",
    "region": "Asia",
    "tz": "Asia/Manila"
  },
  {
    "slug": "maputo",
    "city": "Maputo",
    "region": "Africa",
    "tz": "Africa/Maputo"
  },
  {
    "slug": "marengo",
    "city": "Marengo",
    "region": "America",
    "tz": "America/Indiana/Marengo"
  },
  {
    "slug": "mariehamn",
    "city": "Mariehamn",
    "region": "Europe",
    "tz": "Europe/Mariehamn"
  },
  {
    "slug": "marigot",
    "city": "Marigot",
    "region": "America",
    "tz": "America/Marigot"
  },
  {
    "slug": "marquesas",
    "city": "Marquesas",
    "region": "Pacific",
    "tz": "Pacific/Marquesas"
  },
  {
    "slug": "martinique",
    "city": "Martinique",
    "region": "America",
    "tz": "America/Martinique"
  },
  {
    "slug": "maseru",
    "city": "Maseru",
    "region": "Africa",
    "tz": "Africa/Maseru"
  },
  {
    "slug": "matamoros",
    "city": "Matamoros",
    "region": "America",
    "tz": "America/Matamoros"
  },
  {
    "slug": "mauritius",
    "city": "Mauritius",
    "region": "Indian",
    "tz": "Indian/Mauritius"
  },
  {
    "slug": "mawson",
    "city": "Mawson",
    "region": "Antarctica",
    "tz": "Antarctica/Mawson"
  },
  {
    "slug": "mayotte",
    "city": "Mayotte",
    "region": "Indian",
    "tz": "Indian/Mayotte"
  },
  {
    "slug": "mazatlan",
    "city": "Mazatlan",
    "region": "America",
    "tz": "America/Mazatlan"
  },
  {
    "slug": "mbabane",
    "city": "Mbabane",
    "region": "Africa",
    "tz": "Africa/Mbabane"
  },
  {
    "slug": "mcmurdo",
    "city": "McMurdo",
    "region": "Antarctica",
    "tz": "Antarctica/McMurdo"
  },
  {
    "slug": "melbourne",
    "city": "Melbourne",
    "region": "Australia",
    "tz": "Australia/Melbourne"
  },
  {
    "slug": "mendoza",
    "city": "Mendoza",
    "region": "America",
    "tz": "America/Mendoza"
  },
  {
    "slug": "menominee",
    "city": "Menominee",
    "region": "America",
    "tz": "America/Menominee"
  },
  {
    "slug": "merida",
    "city": "Merida",
    "region": "America",
    "tz": "America/Merida"
  },
  {
    "slug": "metlakatla",
    "city": "Metlakatla",
    "region": "America",
    "tz": "America/Metlakatla"
  },
  {
    "slug": "mexico-city",
    "city": "Mexico City",
    "region": "America",
    "tz": "America/Mexico_City"
  },
  {
    "slug": "midway",
    "city": "Midway",
    "region": "Pacific",
    "tz": "Pacific/Midway"
  },
  {
    "slug": "minsk",
    "city": "Minsk",
    "region": "Europe",
    "tz": "Europe/Minsk"
  },
  {
    "slug": "miquelon",
    "city": "Miquelon",
    "region": "America",
    "tz": "America/Miquelon"
  },
  {
    "slug": "mogadishu",
    "city": "Mogadishu",
    "region": "Africa",
    "tz": "Africa/Mogadishu"
  },
  {
    "slug": "monaco",
    "city": "Monaco",
    "region": "Europe",
    "tz": "Europe/Monaco"
  },
  {
    "slug": "moncton",
    "city": "Moncton",
    "region": "America",
    "tz": "America/Moncton"
  },
  {
    "slug": "monrovia",
    "city": "Monrovia",
    "region": "Africa",
    "tz": "Africa/Monrovia"
  },
  {
    "slug": "monterrey",
    "city": "Monterrey",
    "region": "America",
    "tz": "America/Monterrey"
  },
  {
    "slug": "montevideo",
    "city": "Montevideo",
    "region": "America",
    "tz": "America/Montevideo"
  },
  {
    "slug": "monticello",
    "city": "Monticello",
    "region": "America",
    "tz": "America/Kentucky/Monticello"
  },
  {
    "slug": "montserrat",
    "city": "Montserrat",
    "region": "America",
    "tz": "America/Montserrat"
  },
  {
    "slug": "moscow",
    "city": "Moscow",
    "region": "Europe",
    "tz": "Europe/Moscow"
  },
  {
    "slug": "muscat",
    "city": "Muscat",
    "region": "Asia",
    "tz": "Asia/Muscat"
  },
  {
    "slug": "nairobi",
    "city": "Nairobi",
    "region": "Africa",
    "tz": "Africa/Nairobi"
  },
  {
    "slug": "nassau",
    "city": "Nassau",
    "region": "America",
    "tz": "America/Nassau"
  },
  {
    "slug": "nauru",
    "city": "Nauru",
    "region": "Pacific",
    "tz": "Pacific/Nauru"
  },
  {
    "slug": "ndjamena",
    "city": "Ndjamena",
    "region": "Africa",
    "tz": "Africa/Ndjamena"
  },
  {
    "slug": "new-salem",
    "city": "New Salem",
    "region": "America",
    "tz": "America/North_Dakota/New_Salem"
  },
  {
    "slug": "new-york",
    "city": "New York",
    "region": "America",
    "tz": "America/New_York"
  },
  {
    "slug": "niamey",
    "city": "Niamey",
    "region": "Africa",
    "tz": "Africa/Niamey"
  },
  {
    "slug": "nicosia",
    "city": "Nicosia",
    "region": "Asia",
    "tz": "Asia/Nicosia"
  },
  {
    "slug": "niue",
    "city": "Niue",
    "region": "Pacific",
    "tz": "Pacific/Niue"
  },
  {
    "slug": "nome",
    "city": "Nome",
    "region": "America",
    "tz": "America/Nome"
  },
  {
    "slug": "norfolk",
    "city": "Norfolk",
    "region": "Pacific",
    "tz": "Pacific/Norfolk"
  },
  {
    "slug": "noronha",
    "city": "Noronha",
    "region": "America",
    "tz": "America/Noronha"
  },
  {
    "slug": "nouakchott",
    "city": "Nouakchott",
    "region": "Africa",
    "tz": "Africa/Nouakchott"
  },
  {
    "slug": "noumea",
    "city": "Noumea",
    "region": "Pacific",
    "tz": "Pacific/Noumea"
  },
  {
    "slug": "novokuznetsk",
    "city": "Novokuznetsk",
    "region": "Asia",
    "tz": "Asia/Novokuznetsk"
  },
  {
    "slug": "novosibirsk",
    "city": "Novosibirsk",
    "region": "Asia",
    "tz": "Asia/Novosibirsk"
  },
  {
    "slug": "ojinaga",
    "city": "Ojinaga",
    "region": "America",
    "tz": "America/Ojinaga"
  },
  {
    "slug": "omsk",
    "city": "Omsk",
    "region": "Asia",
    "tz": "Asia/Omsk"
  },
  {
    "slug": "oral",
    "city": "Oral",
    "region": "Asia",
    "tz": "Asia/Oral"
  },
  {
    "slug": "oslo",
    "city": "Oslo",
    "region": "Europe",
    "tz": "Europe/Oslo"
  },
  {
    "slug": "ouagadougou",
    "city": "Ouagadougou",
    "region": "Africa",
    "tz": "Africa/Ouagadougou"
  },
  {
    "slug": "pago-pago",
    "city": "Pago Pago",
    "region": "Pacific",
    "tz": "Pacific/Pago_Pago"
  },
  {
    "slug": "palau",
    "city": "Palau",
    "region": "Pacific",
    "tz": "Pacific/Palau"
  },
  {
    "slug": "palmer",
    "city": "Palmer",
    "region": "Antarctica",
    "tz": "Antarctica/Palmer"
  },
  {
    "slug": "panama",
    "city": "Panama",
    "region": "America",
    "tz": "America/Panama"
  },
  {
    "slug": "paramaribo",
    "city": "Paramaribo",
    "region": "America",
    "tz": "America/Paramaribo"
  },
  {
    "slug": "paris",
    "city": "Paris",
    "region": "Europe",
    "tz": "Europe/Paris"
  },
  {
    "slug": "perth",
    "city": "Perth",
    "region": "Australia",
    "tz": "Australia/Perth"
  },
  {
    "slug": "petersburg",
    "city": "Petersburg",
    "region": "America",
    "tz": "America/Indiana/Petersburg"
  },
  {
    "slug": "phnom-penh",
    "city": "Phnom Penh",
    "region": "Asia",
    "tz": "Asia/Phnom_Penh"
  },
  {
    "slug": "phoenix",
    "city": "Phoenix",
    "region": "America",
    "tz": "America/Phoenix"
  },
  {
    "slug": "pitcairn",
    "city": "Pitcairn",
    "region": "Pacific",
    "tz": "Pacific/Pitcairn"
  },
  {
    "slug": "podgorica",
    "city": "Podgorica",
    "region": "Europe",
    "tz": "Europe/Podgorica"
  },
  {
    "slug": "ponape",
    "city": "Ponape",
    "region": "Pacific",
    "tz": "Pacific/Ponape"
  },
  {
    "slug": "pontianak",
    "city": "Pontianak",
    "region": "Asia",
    "tz": "Asia/Pontianak"
  },
  {
    "slug": "port-moresby",
    "city": "Port Moresby",
    "region": "Pacific",
    "tz": "Pacific/Port_Moresby"
  },
  {
    "slug": "port-of-spain",
    "city": "Port of Spain",
    "region": "America",
    "tz": "America/Port_of_Spain"
  },
  {
    "slug": "port-au-prince",
    "city": "Port-au-Prince",
    "region": "America",
    "tz": "America/Port-au-Prince"
  },
  {
    "slug": "porto-velho",
    "city": "Porto Velho",
    "region": "America",
    "tz": "America/Porto_Velho"
  },
  {
    "slug": "porto-novo",
    "city": "Porto-Novo",
    "region": "Africa",
    "tz": "Africa/Porto-Novo"
  },
  {
    "slug": "prague",
    "city": "Prague",
    "region": "Europe",
    "tz": "Europe/Prague"
  },
  {
    "slug": "puerto-rico",
    "city": "Puerto Rico",
    "region": "America",
    "tz": "America/Puerto_Rico"
  },
  {
    "slug": "punta-arenas",
    "city": "Punta Arenas",
    "region": "America",
    "tz": "America/Punta_Arenas"
  },
  {
    "slug": "pyongyang",
    "city": "Pyongyang",
    "region": "Asia",
    "tz": "Asia/Pyongyang"
  },
  {
    "slug": "qatar",
    "city": "Qatar",
    "region": "Asia",
    "tz": "Asia/Qatar"
  },
  {
    "slug": "qostanay",
    "city": "Qostanay",
    "region": "Asia",
    "tz": "Asia/Qostanay"
  },
  {
    "slug": "qyzylorda",
    "city": "Qyzylorda",
    "region": "Asia",
    "tz": "Asia/Qyzylorda"
  },
  {
    "slug": "rangoon",
    "city": "Rangoon",
    "region": "Asia",
    "tz": "Asia/Rangoon"
  },
  {
    "slug": "rankin-inlet",
    "city": "Rankin Inlet",
    "region": "America",
    "tz": "America/Rankin_Inlet"
  },
  {
    "slug": "rarotonga",
    "city": "Rarotonga",
    "region": "Pacific",
    "tz": "Pacific/Rarotonga"
  },
  {
    "slug": "recife",
    "city": "Recife",
    "region": "America",
    "tz": "America/Recife"
  },
  {
    "slug": "regina",
    "city": "Regina",
    "region": "America",
    "tz": "America/Regina"
  },
  {
    "slug": "resolute",
    "city": "Resolute",
    "region": "America",
    "tz": "America/Resolute"
  },
  {
    "slug": "reunion",
    "city": "Reunion",
    "region": "Indian",
    "tz": "Indian/Reunion"
  },
  {
    "slug": "reykjavik",
    "city": "Reykjavik",
    "region": "Atlantic",
    "tz": "Atlantic/Reykjavik"
  },
  {
    "slug": "riga",
    "city": "Riga",
    "region": "Europe",
    "tz": "Europe/Riga"
  },
  {
    "slug": "rio-branco",
    "city": "Rio Branco",
    "region": "America",
    "tz": "America/Rio_Branco"
  },
  {
    "slug": "rio-gallegos",
    "city": "Rio Gallegos",
    "region": "America",
    "tz": "America/Argentina/Rio_Gallegos"
  },
  {
    "slug": "riyadh",
    "city": "Riyadh",
    "region": "Asia",
    "tz": "Asia/Riyadh"
  },
  {
    "slug": "rome",
    "city": "Rome",
    "region": "Europe",
    "tz": "Europe/Rome"
  },
  {
    "slug": "rothera",
    "city": "Rothera",
    "region": "Antarctica",
    "tz": "Antarctica/Rothera"
  },
  {
    "slug": "saigon",
    "city": "Saigon",
    "region": "Asia",
    "tz": "Asia/Saigon"
  },
  {
    "slug": "saipan",
    "city": "Saipan",
    "region": "Pacific",
    "tz": "Pacific/Saipan"
  },
  {
    "slug": "sakhalin",
    "city": "Sakhalin",
    "region": "Asia",
    "tz": "Asia/Sakhalin"
  },
  {
    "slug": "salta",
    "city": "Salta",
    "region": "America",
    "tz": "America/Argentina/Salta"
  },
  {
    "slug": "samara",
    "city": "Samara",
    "region": "Europe",
    "tz": "Europe/Samara"
  },
  {
    "slug": "samarkand",
    "city": "Samarkand",
    "region": "Asia",
    "tz": "Asia/Samarkand"
  },
  {
    "slug": "san-juan",
    "city": "San Juan",
    "region": "America",
    "tz": "America/Argentina/San_Juan"
  },
  {
    "slug": "san-luis",
    "city": "San Luis",
    "region": "America",
    "tz": "America/Argentina/San_Luis"
  },
  {
    "slug": "san-marino",
    "city": "San Marino",
    "region": "Europe",
    "tz": "Europe/San_Marino"
  },
  {
    "slug": "santarem",
    "city": "Santarem",
    "region": "America",
    "tz": "America/Santarem"
  },
  {
    "slug": "santiago",
    "city": "Santiago",
    "region": "America",
    "tz": "America/Santiago"
  },
  {
    "slug": "santo-domingo",
    "city": "Santo Domingo",
    "region": "America",
    "tz": "America/Santo_Domingo"
  },
  {
    "slug": "sao-paulo",
    "city": "Sao Paulo",
    "region": "America",
    "tz": "America/Sao_Paulo"
  },
  {
    "slug": "sao-tome",
    "city": "Sao Tome",
    "region": "Africa",
    "tz": "Africa/Sao_Tome"
  },
  {
    "slug": "sarajevo",
    "city": "Sarajevo",
    "region": "Europe",
    "tz": "Europe/Sarajevo"
  },
  {
    "slug": "saratov",
    "city": "Saratov",
    "region": "Europe",
    "tz": "Europe/Saratov"
  },
  {
    "slug": "scoresbysund",
    "city": "Scoresbysund",
    "region": "America",
    "tz": "America/Scoresbysund"
  },
  {
    "slug": "seoul",
    "city": "Seoul",
    "region": "Asia",
    "tz": "Asia/Seoul"
  },
  {
    "slug": "shanghai",
    "city": "Shanghai",
    "region": "Asia",
    "tz": "Asia/Shanghai"
  },
  {
    "slug": "simferopol",
    "city": "Simferopol",
    "region": "Europe",
    "tz": "Europe/Simferopol"
  },
  {
    "slug": "singapore",
    "city": "Singapore",
    "region": "Asia",
    "tz": "Asia/Singapore"
  },
  {
    "slug": "sitka",
    "city": "Sitka",
    "region": "America",
    "tz": "America/Sitka"
  },
  {
    "slug": "skopje",
    "city": "Skopje",
    "region": "Europe",
    "tz": "Europe/Skopje"
  },
  {
    "slug": "sofia",
    "city": "Sofia",
    "region": "Europe",
    "tz": "Europe/Sofia"
  },
  {
    "slug": "south-georgia",
    "city": "South Georgia",
    "region": "Atlantic",
    "tz": "Atlantic/South_Georgia"
  },
  {
    "slug": "srednekolymsk",
    "city": "Srednekolymsk",
    "region": "Asia",
    "tz": "Asia/Srednekolymsk"
  },
  {
    "slug": "st-barthelemy",
    "city": "St Barthelemy",
    "region": "America",
    "tz": "America/St_Barthelemy"
  },
  {
    "slug": "st-helena",
    "city": "St Helena",
    "region": "Atlantic",
    "tz": "Atlantic/St_Helena"
  },
  {
    "slug": "st-johns",
    "city": "St Johns",
    "region": "America",
    "tz": "America/St_Johns"
  },
  {
    "slug": "st-kitts",
    "city": "St Kitts",
    "region": "America",
    "tz": "America/St_Kitts"
  },
  {
    "slug": "st-lucia",
    "city": "St Lucia",
    "region": "America",
    "tz": "America/St_Lucia"
  },
  {
    "slug": "st-thomas",
    "city": "St Thomas",
    "region": "America",
    "tz": "America/St_Thomas"
  },
  {
    "slug": "st-vincent",
    "city": "St Vincent",
    "region": "America",
    "tz": "America/St_Vincent"
  },
  {
    "slug": "stanley",
    "city": "Stanley",
    "region": "Atlantic",
    "tz": "Atlantic/Stanley"
  },
  {
    "slug": "stockholm",
    "city": "Stockholm",
    "region": "Europe",
    "tz": "Europe/Stockholm"
  },
  {
    "slug": "swift-current",
    "city": "Swift Current",
    "region": "America",
    "tz": "America/Swift_Current"
  },
  {
    "slug": "sydney",
    "city": "Sydney",
    "region": "Australia",
    "tz": "Australia/Sydney"
  },
  {
    "slug": "syowa",
    "city": "Syowa",
    "region": "Antarctica",
    "tz": "Antarctica/Syowa"
  },
  {
    "slug": "tahiti",
    "city": "Tahiti",
    "region": "Pacific",
    "tz": "Pacific/Tahiti"
  },
  {
    "slug": "taipei",
    "city": "Taipei",
    "region": "Asia",
    "tz": "Asia/Taipei"
  },
  {
    "slug": "tallinn",
    "city": "Tallinn",
    "region": "Europe",
    "tz": "Europe/Tallinn"
  },
  {
    "slug": "tarawa",
    "city": "Tarawa",
    "region": "Pacific",
    "tz": "Pacific/Tarawa"
  },
  {
    "slug": "tashkent",
    "city": "Tashkent",
    "region": "Asia",
    "tz": "Asia/Tashkent"
  },
  {
    "slug": "tbilisi",
    "city": "Tbilisi",
    "region": "Asia",
    "tz": "Asia/Tbilisi"
  },
  {
    "slug": "tegucigalpa",
    "city": "Tegucigalpa",
    "region": "America",
    "tz": "America/Tegucigalpa"
  },
  {
    "slug": "tehran",
    "city": "Tehran",
    "region": "Asia",
    "tz": "Asia/Tehran"
  },
  {
    "slug": "tell-city",
    "city": "Tell City",
    "region": "America",
    "tz": "America/Indiana/Tell_City"
  },
  {
    "slug": "thimphu",
    "city": "Thimphu",
    "region": "Asia",
    "tz": "Asia/Thimphu"
  },
  {
    "slug": "thule",
    "city": "Thule",
    "region": "America",
    "tz": "America/Thule"
  },
  {
    "slug": "tijuana",
    "city": "Tijuana",
    "region": "America",
    "tz": "America/Tijuana"
  },
  {
    "slug": "tirane",
    "city": "Tirane",
    "region": "Europe",
    "tz": "Europe/Tirane"
  },
  {
    "slug": "tokyo",
    "city": "Tokyo",
    "region": "Asia",
    "tz": "Asia/Tokyo"
  },
  {
    "slug": "tomsk",
    "city": "Tomsk",
    "region": "Asia",
    "tz": "Asia/Tomsk"
  },
  {
    "slug": "tongatapu",
    "city": "Tongatapu",
    "region": "Pacific",
    "tz": "Pacific/Tongatapu"
  },
  {
    "slug": "toronto",
    "city": "Toronto",
    "region": "America",
    "tz": "America/Toronto"
  },
  {
    "slug": "tortola",
    "city": "Tortola",
    "region": "America",
    "tz": "America/Tortola"
  },
  {
    "slug": "tripoli",
    "city": "Tripoli",
    "region": "Africa",
    "tz": "Africa/Tripoli"
  },
  {
    "slug": "troll",
    "city": "Troll",
    "region": "Antarctica",
    "tz": "Antarctica/Troll"
  },
  {
    "slug": "truk",
    "city": "Truk",
    "region": "Pacific",
    "tz": "Pacific/Truk"
  },
  {
    "slug": "tucuman",
    "city": "Tucuman",
    "region": "America",
    "tz": "America/Argentina/Tucuman"
  },
  {
    "slug": "tunis",
    "city": "Tunis",
    "region": "Africa",
    "tz": "Africa/Tunis"
  },
  {
    "slug": "ulaanbaatar",
    "city": "Ulaanbaatar",
    "region": "Asia",
    "tz": "Asia/Ulaanbaatar"
  },
  {
    "slug": "ulyanovsk",
    "city": "Ulyanovsk",
    "region": "Europe",
    "tz": "Europe/Ulyanovsk"
  },
  {
    "slug": "urumqi",
    "city": "Urumqi",
    "region": "Asia",
    "tz": "Asia/Urumqi"
  },
  {
    "slug": "ushuaia",
    "city": "Ushuaia",
    "region": "America",
    "tz": "America/Argentina/Ushuaia"
  },
  {
    "slug": "ust-nera",
    "city": "Ust-Nera",
    "region": "Asia",
    "tz": "Asia/Ust-Nera"
  },
  {
    "slug": "utc",
    "city": "UTC",
    "region": "UTC",
    "tz": "UTC"
  },
  {
    "slug": "vaduz",
    "city": "Vaduz",
    "region": "Europe",
    "tz": "Europe/Vaduz"
  },
  {
    "slug": "vancouver",
    "city": "Vancouver",
    "region": "America",
    "tz": "America/Vancouver"
  },
  {
    "slug": "vatican",
    "city": "Vatican",
    "region": "Europe",
    "tz": "Europe/Vatican"
  },
  {
    "slug": "vevay",
    "city": "Vevay",
    "region": "America",
    "tz": "America/Indiana/Vevay"
  },
  {
    "slug": "vienna",
    "city": "Vienna",
    "region": "Europe",
    "tz": "Europe/Vienna"
  },
  {
    "slug": "vientiane",
    "city": "Vientiane",
    "region": "Asia",
    "tz": "Asia/Vientiane"
  },
  {
    "slug": "vilnius",
    "city": "Vilnius",
    "region": "Europe",
    "tz": "Europe/Vilnius"
  },
  {
    "slug": "vincennes",
    "city": "Vincennes",
    "region": "America",
    "tz": "America/Indiana/Vincennes"
  },
  {
    "slug": "vladivostok",
    "city": "Vladivostok",
    "region": "Asia",
    "tz": "Asia/Vladivostok"
  },
  {
    "slug": "volgograd",
    "city": "Volgograd",
    "region": "Europe",
    "tz": "Europe/Volgograd"
  },
  {
    "slug": "vostok",
    "city": "Vostok",
    "region": "Antarctica",
    "tz": "Antarctica/Vostok"
  },
  {
    "slug": "wake",
    "city": "Wake",
    "region": "Pacific",
    "tz": "Pacific/Wake"
  },
  {
    "slug": "wallis",
    "city": "Wallis",
    "region": "Pacific",
    "tz": "Pacific/Wallis"
  },
  {
    "slug": "warsaw",
    "city": "Warsaw",
    "region": "Europe",
    "tz": "Europe/Warsaw"
  },
  {
    "slug": "whitehorse",
    "city": "Whitehorse",
    "region": "America",
    "tz": "America/Whitehorse"
  },
  {
    "slug": "winamac",
    "city": "Winamac",
    "region": "America",
    "tz": "America/Indiana/Winamac"
  },
  {
    "slug": "windhoek",
    "city": "Windhoek",
    "region": "Africa",
    "tz": "Africa/Windhoek"
  },
  {
    "slug": "winnipeg",
    "city": "Winnipeg",
    "region": "America",
    "tz": "America/Winnipeg"
  },
  {
    "slug": "yakutat",
    "city": "Yakutat",
    "region": "America",
    "tz": "America/Yakutat"
  },
  {
    "slug": "yakutsk",
    "city": "Yakutsk",
    "region": "Asia",
    "tz": "Asia/Yakutsk"
  },
  {
    "slug": "yekaterinburg",
    "city": "Yekaterinburg",
    "region": "Asia",
    "tz": "Asia/Yekaterinburg"
  },
  {
    "slug": "yerevan",
    "city": "Yerevan",
    "region": "Asia",
    "tz": "Asia/Yerevan"
  },
  {
    "slug": "zagreb",
    "city": "Zagreb",
    "region": "Europe",
    "tz": "Europe/Zagreb"
  },
  {
    "slug": "zurich",
    "city": "Zurich",
    "region": "Europe",
    "tz": "Europe/Zurich"
  },
  {
    "slug": "mumbai",
    "city": "Mumbai",
    "region": "Asia",
    "tz": "Asia/Kolkata"
  },
  {
    "slug": "bangalore",
    "city": "Bangalore",
    "region": "Asia",
    "tz": "Asia/Kolkata"
  },
  {
    "slug": "chennai",
    "city": "Chennai",
    "region": "Asia",
    "tz": "Asia/Kolkata"
  },
  {
    "slug": "hyderabad",
    "city": "Hyderabad",
    "region": "Asia",
    "tz": "Asia/Kolkata"
  },
  {
    "slug": "pune",
    "city": "Pune",
    "region": "Asia",
    "tz": "Asia/Kolkata"
  },
  {
    "slug": "delhi",
    "city": "Delhi",
    "region": "Asia",
    "tz": "Asia/Kolkata"
  },
  {
    "slug": "kolkata",
    "city": "Kolkata",
    "region": "Asia",
    "tz": "Asia/Kolkata"
  },
  {
    "slug": "san-francisco",
    "city": "San Francisco",
    "region": "America",
    "tz": "America/Los_Angeles"
  },
  {
    "slug": "seattle",
    "city": "Seattle",
    "region": "America",
    "tz": "America/Los_Angeles"
  },
  {
    "slug": "las-vegas",
    "city": "Las Vegas",
    "region": "America",
    "tz": "America/Los_Angeles"
  },
  {
    "slug": "san-diego",
    "city": "San Diego",
    "region": "America",
    "tz": "America/Los_Angeles"
  },
  {
    "slug": "boston",
    "city": "Boston",
    "region": "America",
    "tz": "America/New_York"
  },
  {
    "slug": "washington-dc",
    "city": "Washington DC",
    "region": "America",
    "tz": "America/New_York"
  },
  {
    "slug": "miami",
    "city": "Miami",
    "region": "America",
    "tz": "America/New_York"
  },
  {
    "slug": "atlanta",
    "city": "Atlanta",
    "region": "America",
    "tz": "America/New_York"
  },
  {
    "slug": "houston",
    "city": "Houston",
    "region": "America",
    "tz": "America/Chicago"
  },
  {
    "slug": "dallas",
    "city": "Dallas",
    "region": "America",
    "tz": "America/Chicago"
  },
  {
    "slug": "munich",
    "city": "Munich",
    "region": "Europe",
    "tz": "Europe/Berlin"
  },
  {
    "slug": "frankfurt",
    "city": "Frankfurt",
    "region": "Europe",
    "tz": "Europe/Berlin"
  },
  {
    "slug": "milan",
    "city": "Milan",
    "region": "Europe",
    "tz": "Europe/Rome"
  },
  {
    "slug": "manchester",
    "city": "Manchester",
    "region": "Europe",
    "tz": "Europe/London"
  },
  {
    "slug": "barcelona",
    "city": "Barcelona",
    "region": "Europe",
    "tz": "Europe/Madrid"
  },
  {
    "slug": "osaka",
    "city": "Osaka",
    "region": "Asia",
    "tz": "Asia/Tokyo"
  },
  {
    "slug": "doha",
    "city": "Doha",
    "region": "Asia",
    "tz": "Asia/Qatar"
  },
  {
    "slug": "tel-aviv",
    "city": "Tel Aviv",
    "region": "Asia",
    "tz": "Asia/Jerusalem"
  },
  {
    "slug": "beijing",
    "city": "Beijing",
    "region": "Asia",
    "tz": "Asia/Shanghai"
  }
];

// Slugs pre-built as static pSEO pages (see [from]-to-[to].astro). Any OTHER
// city is still fully usable via the client-side Universal Converter search —
// nothing here limits what a visitor can actually convert.
export const FEATURED_SLUGS: string[] = [
  "utc",
  "new-york",
  "los-angeles",
  "chicago",
  "denver",
  "toronto",
  "vancouver",
  "mexico-city",
  "sao-paulo",
  "buenos-aires",
  "london",
  "paris",
  "berlin",
  "madrid",
  "rome",
  "amsterdam",
  "dublin",
  "lisbon",
  "zurich",
  "moscow",
  "istanbul",
  "athens",
  "dubai",
  "riyadh",
  "doha",
  "tel-aviv",
  "mumbai",
  "kolkata",
  "delhi",
  "karachi",
  "dhaka",
  "bangkok",
  "jakarta",
  "singapore",
  "kuala-lumpur",
  "manila",
  "hong-kong",
  "shanghai",
  "beijing",
  "seoul",
  "tokyo",
  "sydney",
  "melbourne",
  "auckland",
  "johannesburg",
  "cairo",
  "lagos",
  "nairobi",
  "san-francisco",
  "boston"
];

export const FEATURED_TIMEZONES: TZCity[] = ALL_TIMEZONES.filter((t) =>
  FEATURED_SLUGS.includes(t.slug)
);

export function findCity(slug: string): TZCity | undefined {
  return ALL_TIMEZONES.find((t) => t.slug === slug);
}
